name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download

        run: curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update
      - run: sudo apt install ngrok

      - name: Auth

        run: ngrok authtoken $Env:NGROK_AUTH_TOKEN

        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          ARGS: "-av"


      - name: Enable TS
        run: |
         sudo apt-get update
         sudo add-apt-repository universe
         sudo apt-get update
         sudo apt-get install chntpw
         sudo chntpw -e /path/to/SYSTEM -t 0x3e 'ControlSet001\Control\Terminal Server' << EOF
         ed fDenyTSConnections
         0
         q
         y
         EOF

      - name: Enable Net Firewall Rule
        run: sudo ufw allow 3389/tcp

      - name: Set User Authentication
        run: |
         sudo chntpw -e /path/to/SYSTEM -t 0x3e 'ControlSet001\Control\Terminal Server\WinStations\RDP-Tcp' << EOF
         ed UserAuthentication
         1
         q
         y
         EOF

      - name: Set Local User Password
        run: |
         sudo usermod --password $(echo "P@ssw0rd!" | openssl passwd -1 -stdin) runneradmin


      - name: Create Tunnel

        run: .\ngrok\ngrok.exe tcp 3389
        
